### ISSUE TITLE
uninstall commandbox-fusionreactor no longer seems to work

### ISSUE THREAD

**Issue by neilwightman-intergral** [bdw429s/commandbox-fusionreactor#14]
When installing commandbox-fusionreactor everything works fine, but uninstall doesnt appear to work any more.

```
cd ~/coldbox/
install commandbox-fusionreactor
box install
server start
-- has FR running as expected
server stop
uninstall commandbox-fusionreactor --system
uninstall commandbox-fusionreactor
server start
-- still has FR running
```

You must restart commadbox for the uninstall to work now.  Is there anything that can be done to make commandbox know that we uninstall this module or do you have to restart commandbox is you uninstall any module?

**Comment by neilwightman-intergral** [comment]
I cannot see where the dependency is being cached
```
CommandBox> server show
{
    "web":{
        "rewrites":{
            "enable":true
        }
    }
}
```

```
CommandBox> package list
Dependency Hierarchy for My ColdBox App (1.0.0)
├─┬ coldbox (5.5.0+958)
│ └── testbox ()
└── testbox (2.8.0+191)
```

**Comment by bdw429s** [comment]
@neilwightman-intergral  That's correct, any time you uninstall a system module, it's still going to be loaded into memory in the CLI until you restart the CLI.  We can probably add a generic enhancement to CommandBox to try and detect that.  Can you put in a ticket for CommandBox for this?

**Comment by bdw429s** [comment]
Closing this as it's not any sort of defect in the module itself, just a misunderstanding that a CommandBox `reload` is needed if you uninstall a system module and haven't restarted the CLI.
