### ISSUE TITLE
Fusion Reactor 7.4.1

### ISSUE THREAD

**Issue by iknowkungfoo** [bdw429s/commandbox-fusionreactor#9]
Currently installing FR 7.3.1.

http://www.fusion-reactor.com/news/fusionreactor-7-4-1-adds-support-for-async-functionality-in-coldfusion-2018/

**Comment by bdw429s** [comment]
Thanks @iknowkungfoo .  I just committed a bump for the version and the Travis build should release a new version to ForgeBox in a few minutes
